version: 2.1

orbs:
  unity: game-ci/unity@1.4.0
  aws-s3: circleci/aws-s3@3.1

jobs:
  build:
    executor:
      name: "unity/ubuntu"
      target_platform: "webgl"
      editor_version: "2021.3.9f1"
      resource_class: "large"
    steps:
      - checkout
      - unity/prepare-env:
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
      - unity/build:
          project-path: "src"
          build-target: "WebGL"
          compress: false
          store-artifacts: false
      - persist_to_workspace:
          root: .
          paths:
            - "src/Builds/WebGL"
