version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:
  build-unity-project:
    jobs:
      - unity/test:
          name: "test-linux"
          step-name: "Check if the tests run and results are uploaded"
          # unity-license-var-name: "UNITY_ENCODED_LICENSE"
          # unity-username-var-name: "UNITY_USERNAME"
          # unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2022.3.5f1"
            resource_class: "medium"
          project-path: "src"
          test-platform: "playmode"
          context: unity
      - unity/build:
          name: "build-webgl"
          step-name: "Build WebGL"
          # unity-license-var-name: "UNITY_ENCODED_LICENSE"
          # unity-username-var-name: "UNITY_USERNAME"
          # unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "webgl"
            editor_version: "2022.3.5f1"
            resource_class: "large"
          project-path: "src"
          build-target: "WebGL"
          compress: false
          context: unity